// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBv_nujVde71QRsZ7V7ElDZzLHlXxhJSAM',
    appId: '1:623424112729:web:c01f3038b1ce7377d54948',
    messagingSenderId: '623424112729',
    projectId: 'e-belediyecilik',
    authDomain: 'e-belediyecilik.firebaseapp.com',
    storageBucket: 'e-belediyecilik.appspot.com',
    measurementId: 'G-DMQT31VZR1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvgvYy8ElC1R3oelJz7ZlkmQ1061O80OA',
    appId: '1:623424112729:android:08c0881a9acaa491d54948',
    messagingSenderId: '623424112729',
    projectId: 'e-belediyecilik',
    storageBucket: 'e-belediyecilik.appspot.com',
  );

}